### PR TITLE
Exports common and helpers files

### PR DESCRIPTION
**Pull request by jaspervriends**
**Changes proposed in this pull request:**
Exports `common` and `helpers` files for developers.

Files are exported to:
```
flarum.extensions['fof-nightmode']['forum']["fof/nightmode/getTheme"]
```

Files are accessible via their own full path, such as `flarum.extensions['fof-nightmode']['forum']["fof/nightmode/getTheme"]`

### CODE REVIEW

**Review by davwheat — COMMENTED** [review]
When exporting, we shouldn't add the package namespace to the keys. For example, `"fof/nightmode/getTheme"` should be just `"getTheme"`.

Also, stuff in the `common` dir should really be exported in both `forum` and `admin`, both _without_ the `common` prefix. The best way to do this would be to...

`js/src/common/index.ts`:
```ts
export { default as Themes } from './Themes';
// ...
```

`js/forum.js`:
```ts
export * from './forum'
export * from './common'
```

and the same in `js/admin.js`

---

The reasoning for this is that, if you want to extend Nightmode in your own extension, you should set up your `webpack.config.js` with the `useExtensions` option (see https://github.com/flarum/flarum-webpack-config#useextensions).

This allows you to just:

```ts
import Themes from '@fof-nightmode/Themes`;
```

Or, if the ext is an optional dependency...

```ts
// ...

if ('fof-nightmode' in flarum.extensions) {
  const Themes = require(`@fof-nightmode`);

  // ...
}
```

**Comment by jaspervriends** [comment]
Thanks for the feedback! Fixed @davwheat it :)

**Comment by datitisev** [comment]
Just to clarify something, the `useExtensions` option in webpack config does _not_ allow for `import Themes from '@fof-nightmode/Themes';`.
[It only adds the `@fof-nightmode` import](https://github.com/flarum/flarum-webpack-config/blob/f27afcb0699fa65e118fd0dc29826d8c1b08afd9/index.js#L126-L129) and the inside of that is accessed like a regular object.



So it'd be
```js
import { Themes } from '@fof-nightmode';
```

**Review by davwheat — APPROVED** [review]
Looks good, but I (or someone else) should probably test locally tomorrow just to double check.

**Comment by jaspervriends** [comment]
Thanks! I already got it working for my custom switch component. But I'll wait for the check :)

[Image from Gyazo](https://gyazo.com/ecc69a965951b34afd05321ef7f8b537)

**Pull request merged**
